services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    environment:
      # Set Frontend ENV Variables Here
      - API_URL=http://localhost:9000 #
    restart:
      always
      #ports:
      #- "9925:3000" #
    volumes:
      - /nvme/docker/mealie/data/:/app/data/ #
    network_mode: service:ts-mealie
    depends_on:
      - ts-mealie
      - mealie-api
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
      - /nvme/docker/mealie/data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DEFAULT_EMAIL=contact@florianveaux.fr
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      #- BASE_URL=https://mealie.florianveaux.fr
    restart: always
    network_mode: service:ts-mealie
    depends_on:
      - ts-mealie
  ts-mealie:
    image: tailscale/tailscale:latest
    container_name: ts-mealie
    hostname: mealie
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
        #- TS_SERVE_CONFIG=/config/mealie.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /nvme/docker/mealie/ts/state:/var/lib/tailscale
      - /nvme/docker/mealie/ts/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
