---
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000 # 
    restart: always
    ports:
      - "9925:3000" # 
    volumes:
      - /nvme/docker/mealie/data/:/app/data/ # 
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /nvme/docker/mealie/data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DEFAULT_EMAIL=contact@florianveaux.fr
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.florianveaux.fr
    restart: always
networks:
  default:
    external:
      name: nginx_proxy_manager
