services:
  npm:
    container_name: "nginx_proxy_manager"
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "192.168.1.2:80:80"
      - "192.168.1.2:443:443"
      - "81:81"
    networks:
      - nginx_proxy_manager
      - datadog-agent
    labels:
      com.datadoghq.ad.check_names: '["nginx"]'
      com.datadoghq.ad.init_configs: "[{}]"
      com.datadoghq.ad.instances: '[{"nginx_status_url": "http://%%host_datadog-agent%%:82/nginx_status/"}]'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - /nvme/docker/nginx_proxy/data:/data
      - /nvme/docker/nginx_proxy/etc/letsencrypt:/etc/letsencrypt
networks:
  nginx_proxy_manager:
    name: nginx_proxy_manager
  datadog-agent:
    name: datadog-agent
    external: true
