version: '3'
services:
  npm:
    container_name: "nginx_proxy_manager"
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - /nvme/docker/nginx_proxy/data:/data
      - /nvme/docker/nginx_proxy/etc/letsencrypt:/etc/letsencrypt
networks:
  default:
    name: nginx_proxy_manager
