version: '3'
services:
  datadog:
    restart: always
    container_name: dd-agent
    image: datadog/agent:latest
    environment:
     - DD_API_KEY=${DD_API_KEY}
     - DD_SITE=datadoghq.eu
     - DD_LOGS_ENABLED=true
     - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
     - DD_DOGSTATSD_SOCKET=/var/run/datadog/dogstatsd.socket
    volumes:
     - /nvme/docker/datadog-agent/dogstatsd.socket:/var/run/datadog/dogstatsd.socket
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
     - /var/lib/docker/containers:/var/lib/docker/containers:ro
