version: '3'
services:
  fnf_wedding:
    restart: always
    container_name: fnf_wedding
    image: hcr.florianveaux.fr/fnf-savethedate
    volumes:
      - /nvme/docker/fnf_website/productiondb.sqlite:/app/productiondb.sqlite
