version: '3'
services:
  app:
    container_name: portainer
    image: 'portainer/portainer-ce:latest'
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /nvme/docker/portainer/data:/data
networks:
  default:
    external:
      name: nginx_proxy_manager
