version: '3'
services:
  app:
    image: 'portainer/portainer-ce:latest'
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/homelab/docker/portainer/data:/data
