services:
  app:
    container_name: portainer
    image: "portainer/portainer-ce:latest"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /nvme/docker/portainer/data:/data
  ts-portainer:
    image: tailscale/tailscale:latest
    container_name: ts-mealie
    hostname: portainer
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /nvme/docker/portainer/ts/state:/var/lib/tailscale
      - /nvme/docker/portainer/ts/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
